
// This file has been generated by the GUI designer. Do not modify.
namespace CVector
{
	public partial class ActionGroup
	{
		public virtual void Build ()
		{
			// Action group CVector.ActionGroup
		}
	}
}
